title = "heyo"
theme = "heyo"
baseURL = "/"
languageCode = "en"
DefaultContentLanguage = "en"
summarylength = 100
enableEmoji = true
enableRobotsTXT = true
paginate = 10

# Disqus comments
# https://gohugo.io/templates/internal/#configure-disqus
# disqusShortname = ""

# Google Analytics
# https://gohugo.io/templates/internal/#google-analytics
# googleAnalytics = ""

[Languages]
  [Languages.en]
    contentDir = "content/en"
    weight = 1
    LanguageName = "en"

[params.author]
  name = "Jamie Nunez"
  email = "jamie.nunez01@gmail.com"

[params]
  title = "Welcome"
  description = ""
  profilePicture = "images/profile.jpg"
  favicon = "favicons/"
  customCss = []
  customJs = []
  displayMode = "dark"
  images = ['images/profile.jpg']

[taxonomies]
  series = 'series'

# Sketch settings
# you can also enable or disable it per page
[params.sketch] 
  enable = true 
  displayOptions = false
  # Graph, Digital Rain, or Circles
  use = "Graph"
  # JSON that is passed to the sketch constructor
  # You can check all the possible configurations in
  startingConfig = """{
    "kind": "katakana",
    "nStreams": 10
  }"""


## Math settings
[params.math]
  # global support, you can also configure it per page
  enable = true
  # katex or mathjax, default is mathjax
  use = "mathjax"

## Social links
[[params.socialIcons]]
icon = "fab fa-linkedin" # Font-awesome icon
title = "Linkedin"
url = "https://www.linkedin.com/in/jamienunez1607/"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/jamienunez"

[[params.socialIcons]]
icon = "fas fa-book"
title = "Google Scholar"
url = "https://scholar.google.com/citations?user=sv-iR1YAAAAJ&hl=en"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:jamie.nunez01@gmail.com"

# Menu items
[menu]
[[Languages.en.menu.main]]
name = "Home"
identifier = "home"
weight = 100
url = "/"

[[Languages.en.menu.main]]
name = "Projects"
weight = 200
identifier = "projects"
url = "/projects/"

[[Languages.en.menu.main]]
name = "About"
weight = 300
identifier = "about"
url = "/about/"


[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableOfContents]
    endLevel = 6
    startLevel = 1
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "dracula"
    tabWidth = 4

# Hugo will ignore these files, .rmd and .rmarkdown are taken care by blogdown
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown", "_files$", "_cache$"]